/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: GranD (https://sketchfab.com/grandFX)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/iron-man-69dde1ad49e94852984e3d83928efd65
title: Iron Man
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Model({ ...props }) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/scene.gltf");
  console.log(nodes);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials["default"]}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials["default"]}
        />
        <mesh
          geometry={nodes.Object_4.geometry}
          material={materials["default"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/scene.gltf");
